// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace StudentPreferenceAiModelDemoML.Model
{
    public class ModelInput
    {
        [ColumnName("ID"), LoadColumn(0)]
        public float ID { get; set; }


        [ColumnName("Preference"), LoadColumn(1)]
        public string Preference { get; set; }


        [ColumnName("Description"), LoadColumn(2)]
        public string Description { get; set; }


    }
}
