// This file was auto-generated by ML.NET Model Builder. 

using System;
using StudentPreferenceAiModelDemoML.Model;

namespace StudentPreferenceAiModelDemoML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Description = @"When trying to remember someone�s telephone number, or something new, it helps me to get a picture of it in my mind",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Preference with predicted Preference from sample data...\n\n");
            Console.WriteLine($"Description: {sampleData.Description}");
            Console.WriteLine($"\n\nPredicted Preference value {predictionResult.Prediction} \nPredicted Preference scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
